shallow_clone: true

environment:
  matrix:
  - LUA: "lua=5.1"
  - LUA: "lua=5.2"
  - LUA: "lua=5.3"
  - LUA: "lua=5.4"
  - LUA: "luajit=2.0"
  - LUA: "luajit=2.1"

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - hererocks lua_install --%LUA% -r latest
  - call lua_install\bin\activate
  - luarocks install busted
  - luarocks install luacheck
  - luarocks install rocks-fun --dev

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks make

before_test:
- luarocks install rocks-fun --dev
- luarocks install tl

test_script:
- echo "Type check..."
- tl check src/rocks/fun.d.tl
- echo "Testing..."
- lua spec/rocksfun_spec.lua

after_test:
# @todo